model_path:
  small: "D:\\Local_multilmodal_ai_chat\\models\\mistral-7b-instruct-v0.1.Q3_K_M.gguf"
  large: "D:\\Local_multilmodal_ai_chat\\models\\mistral-7b-instruct-v0.1.Q5_K_M.gguf"

model_type: "mistral"

model_config: {'max_new_tokens': 512, 'temperature' : 0.4, 'context_length': 4096, 'gpu_layers': 0}

embeddings_path: "BAAI/bge-large-en-v1.5"

chat_history_path: "./chat_sessions/"
